services:
  # Backend API Service
  - type: web
    name: hawaii-emergency-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hawaii-emergency-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://hawaii-emergency-hub.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@hawaii-emergency.gov
      - key: ADMIN_PASSWORD
        generateValue: true
    healthCheckPath: /
    region: oregon
    plan: free

  # Frontend Dashboard (Alternative to Vercel)
  # - type: web
  #   name: hawaii-emergency-dashboard
  #   runtime: docker
  #   dockerfilePath: ./web-dashboard/Dockerfile
  #   dockerContext: ./web-dashboard
  #   envVars:
  #     - key: NEXT_PUBLIC_API_URL
  #       value: https://hawaii-emergency-backend.onrender.com/api/v1
  #   region: oregon
  #   plan: free

databases:
  - name: hawaii-emergency-db
    databaseName: hawaii_emergency
    plan: free
    postgresMajorVersion: 15